import sys
import sysconfig
from pathlib import Path

import pytest

from amigafs.errors import AmigaFSError
from amigafs.nautilus_install import (
    DESKTOP_FILE_NAME,
    MIME_PACKAGE_NAME,
    MIME_TYPES,
    desktop_file_path,
    install_extension,
    mime_package_path,
    uninstall_extension,
)


def test_installs_and_removes_complete_desktop_integration(
    tmp_path: Path, monkeypatch: object
) -> None:
    monkeypatch.setenv("XDG_DATA_HOME", str(tmp_path))  # type: ignore[attr-defined]
    target = install_extension()
    content = target.read_text(encoding="utf-8")
    assert target == tmp_path / "nautilus-python" / "extensions" / "nautilus_amigafs.py"
    assert repr(sys.executable) in content
    assert str(sysconfig.get_path("purelib")) in content
    assert "AmigaFSMenuProvider" in content
    assert "AmigaFSPropertiesModelProvider" in content
    mime_content = mime_package_path().read_text(encoding="utf-8")
    assert mime_package_path() == tmp_path / "mime" / "packages" / MIME_PACKAGE_NAME
    assert 'type="application/x-amiga-disk-format"' in mime_content
    assert 'value="DOS\\000" offset="0"' in mime_content
    assert 'value="DOS\\007" offset="0"' in mime_content
    assert 'type="application/x-amiga-hard-disk"' in mime_content
    assert 'value="RDSK" offset="0:7680"' in mime_content
    # Suffixes shared with other systems are claimed below their content magic.
    assert '<glob pattern="*.adf" weight="55"/>' in mime_content
    assert '<glob pattern="*.hdf" weight="55"/>' in mime_content
    for pattern in ("*.adz", "*.hdz", "*.dms", "*.hfe", "*.scp", "*.ipf", "*.kick"):
        assert f'pattern="{pattern}"' in mime_content
    for generic in ("*.rom", "*.img", "*.raw", "*.dat", "*.gz"):
        assert f'pattern="{generic}"' not in mime_content
    assert 'value="DMS!" offset="0"' in mime_content
    assert 'value="UAE-1ADF" offset="0"' in mime_content
    assert 'value="HXCPICFE" offset="0"' in mime_content
    assert 'value="HXCHFEV3" offset="0"' in mime_content
    assert "acorn" not in mime_content.casefold()
    desktop_content = desktop_file_path().read_text(encoding="utf-8")
    assert desktop_file_path() == tmp_path / "applications" / DESKTOP_FILE_NAME
    assert "desktop-open %U" in desktop_content
    assert "x-scheme-handler/amigafs" in desktop_content
    for mime_type in MIME_TYPES:
        assert f"{mime_type};" in desktop_content
        assert f'type="{mime_type}"' in mime_content
    assert "NoDisplay=true" in desktop_content
    assert uninstall_extension() == target
    assert not target.exists()
    assert not mime_package_path().exists()
    assert not desktop_file_path().exists()


def test_refuses_to_remove_foreign_extension(tmp_path: Path, monkeypatch: object) -> None:
    monkeypatch.setenv("XDG_DATA_HOME", str(tmp_path))  # type: ignore[attr-defined]
    target = tmp_path / "nautilus-python" / "extensions" / "nautilus_amigafs.py"
    target.parent.mkdir(parents=True)
    target.write_text("# user file\n", encoding="utf-8")
    with pytest.raises(AmigaFSError, match="Refusing"):
        uninstall_extension()


def test_install_removes_generated_legacy_bootstrap(tmp_path: Path, monkeypatch: object) -> None:
    monkeypatch.setenv("XDG_DATA_HOME", str(tmp_path))  # type: ignore[attr-defined]
    legacy = tmp_path / "nautilus-python" / "extensions" / "amigafs.py"
    legacy.parent.mkdir(parents=True)
    legacy.write_text("# Generated by amigafs install-nautilus\n", encoding="utf-8")
    install_extension()
    assert not legacy.exists()


def test_mime_package_is_accepted_by_the_shared_mime_database(tmp_path: Path) -> None:
    import shutil
    import subprocess

    from amigafs.nautilus_install import mime_package_content

    tool = shutil.which("update-mime-database")
    if tool is None:
        pytest.skip("shared-mime-info is not installed")
    packages = tmp_path / "packages"
    packages.mkdir()
    (packages / MIME_PACKAGE_NAME).write_text(mime_package_content(), encoding="utf-8")
    result = subprocess.run([tool, str(tmp_path)], check=False, capture_output=True, text=True)
    assert result.returncode == 0
    assert "rror" not in result.stderr.replace("XDG_DATA", "")
    generated = {path.name for path in (tmp_path / "application").iterdir()}
    assert generated == {f"{mime_type.split('/')[1]}.xml" for mime_type in MIME_TYPES}
