"""Per-user installation of the Nautilus Python extension."""

from __future__ import annotations

import os
import pwd
import shutil
import subprocess
import sys
import sysconfig
import uuid
from pathlib import Path

from amigafs.errors import AmigaFSError

MARKER = "# Generated by amigafs install-nautilus"
XML_MARKER = "<!-- Generated by amigafs install-nautilus -->"
EXTENSION_NAME = "nautilus_amigafs.py"
LEGACY_EXTENSION_NAME = "amigafs.py"
MIME_PACKAGE_NAME = "amigafs.xml"
DESKTOP_FILE_NAME = "org.amigafs.NautilusAmigaFS.desktop"


def data_home() -> Path:
    configured = os.environ.get("XDG_DATA_HOME")
    if configured:
        return Path(configured).expanduser()
    account_home = Path(pwd.getpwuid(os.getuid()).pw_dir)
    return account_home / ".local" / "share"


def extension_path() -> Path:
    return data_home() / "nautilus-python" / "extensions" / EXTENSION_NAME


def mime_package_path() -> Path:
    return data_home() / "mime" / "packages" / MIME_PACKAGE_NAME


def desktop_file_path() -> Path:
    return data_home() / "applications" / DESKTOP_FILE_NAME


def _generated_exists(target: Path, *, marker: str = MARKER) -> bool:
    if not target.exists():
        return False
    try:
        first_line = target.read_text(encoding="utf-8").splitlines()[0]
    except (OSError, UnicodeError, IndexError) as exc:
        raise AmigaFSError(f"Cannot verify installed integration file {target}: {exc}") from exc
    if first_line != marker:
        raise AmigaFSError(
            f"Refusing to modify an integration file not created by AmigaFS: {target}"
        )
    return True


def _remove_if_generated(target: Path, *, marker: str = MARKER) -> bool:
    if not _generated_exists(target, marker=marker):
        return False
    target.unlink()
    return True


def _write_generated(target: Path, content: str, *, marker: str = MARKER) -> None:
    target.parent.mkdir(mode=0o755, parents=True, exist_ok=True)
    _generated_exists(target, marker=marker)
    temporary = target.with_name(f".{target.name}.{uuid.uuid4().hex}.tmp")
    try:
        with temporary.open("x", encoding="utf-8") as handle:
            handle.write(content)
            handle.flush()
            os.fsync(handle.fileno())
        temporary.chmod(0o644)
        temporary.replace(target)
    finally:
        temporary.unlink(missing_ok=True)


def _desktop_quote(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"').replace("`", "\\`")
    escaped = escaped.replace("$", "\\$").replace("%", "%%")
    return f'"{escaped}"'


MIME_TYPES = (
    "application/x-amiga-disk-format",
    "application/x-amiga-hard-disk",
    "application/x-amiga-compressed-disk",
    "application/x-amiga-extended-adf",
    "application/x-amiga-kickstart",
    "application/x-diskmasher",
    "application/x-hxc-hfe",
    "application/x-supercardpro",
    "application/x-ipf-disk",
)


def mime_package_content() -> str:
    """Return the shared MIME package used by user and system installations.

    Every type that shares a suffix with another system is identified by content
    magic, so an Acorn ``.adf`` or ``.hdf`` is left to whatever handles those.
    """

    return f"""{XML_MARKER}
<mime-info xmlns="http://www.freedesktop.org/standards/shared-mime-info">
  <mime-type type="application/x-amiga-disk-format">
    <comment>Amiga floppy disk image</comment>
    <magic priority="85">
      <match type="string" value="DOS\\000" offset="0"/>
      <match type="string" value="DOS\\001" offset="0"/>
      <match type="string" value="DOS\\002" offset="0"/>
      <match type="string" value="DOS\\003" offset="0"/>
      <match type="string" value="DOS\\004" offset="0"/>
      <match type="string" value="DOS\\005" offset="0"/>
      <match type="string" value="DOS\\006" offset="0"/>
      <match type="string" value="DOS\\007" offset="0"/>
    </magic>
    <glob pattern="*.adf" weight="55"/>
  </mime-type>
  <mime-type type="application/x-amiga-hard-disk">
    <comment>Amiga hard-disc image</comment>
    <magic priority="85">
      <match type="string" value="RDSK" offset="0:7680"/>
      <match type="string" value="PFS\\001" offset="0"/>
      <match type="string" value="PFS\\002" offset="0"/>
      <match type="string" value="PFS\\003" offset="0"/>
      <match type="string" value="PDS\\003" offset="0"/>
      <match type="string" value="SFS\\000" offset="0"/>
    </magic>
    <glob pattern="*.hdf" weight="55"/>
    <glob pattern="*.hda" weight="70"/>
    <glob pattern="*.rdsk" weight="70"/>
  </mime-type>
  <mime-type type="application/x-amiga-compressed-disk">
    <comment>Compressed Amiga disk image</comment>
    <sub-class-of type="application/gzip"/>
    <glob pattern="*.adz" weight="70"/>
    <glob pattern="*.ADZ" weight="70"/>
    <glob pattern="*.hdz" weight="70"/>
    <glob pattern="*.HDZ" weight="70"/>
  </mime-type>
  <mime-type type="application/x-amiga-extended-adf">
    <comment>Amiga extended disk image</comment>
    <magic priority="90">
      <match type="string" value="UAE--ADF" offset="0"/>
      <match type="string" value="UAE-1ADF" offset="0"/>
    </magic>
  </mime-type>
  <mime-type type="application/x-amiga-kickstart">
    <comment>Amiga Kickstart ROM</comment>
    <magic priority="60">
      <match type="big32" value="0x11114ef9" offset="0"/>
      <match type="big32" value="0x11144ef9" offset="0"/>
    </magic>
    <glob pattern="*.kick" weight="70"/>
  </mime-type>
  <mime-type type="application/x-diskmasher">
    <comment>DiskMasher disk archive</comment>
    <magic priority="90">
      <match type="string" value="DMS!" offset="0"/>
    </magic>
    <glob pattern="*.dms" weight="70"/>
    <glob pattern="*.DMS" weight="70"/>
  </mime-type>
  <mime-type type="application/x-hxc-hfe">
    <comment>HxC HFE floppy image</comment>
    <magic priority="90">
      <match type="string" value="HXCPICFE" offset="0"/>
      <match type="string" value="HXCHFEV3" offset="0"/>
    </magic>
    <glob pattern="*.hfe" weight="70"/>
    <glob pattern="*.HFE" weight="70"/>
  </mime-type>
  <mime-type type="application/x-supercardpro">
    <comment>SuperCard Pro flux image</comment>
    <magic priority="70">
      <match type="string" value="SCP" offset="0"/>
    </magic>
    <glob pattern="*.scp" weight="70"/>
    <glob pattern="*.SCP" weight="70"/>
  </mime-type>
  <mime-type type="application/x-ipf-disk">
    <comment>SPS preservation disk image</comment>
    <magic priority="90">
      <match type="string" value="CAPS" offset="0"/>
    </magic>
    <glob pattern="*.ipf" weight="70"/>
    <glob pattern="*.IPF" weight="70"/>
  </mime-type>
</mime-info>
"""


def desktop_file_content(command: list[str] | None = None) -> str:
    """Return the desktop handler for an explicit, shell-free command."""

    selected = command or [sys.executable, "-m", "amigafs.cli"]
    executable = " ".join(_desktop_quote(part) for part in selected)
    mime_types = ";".join((*MIME_TYPES, "x-scheme-handler/amigafs"))
    return f"""{MARKER}
[Desktop Entry]
Type=Application
Name=AmigaFS Image Mounter
Comment=Open a supported Amiga disk image read-only
Exec={executable} desktop-open %U
Icon=drive-harddisk
Terminal=false
NoDisplay=true
StartupNotify=true
MimeType={mime_types};
Categories=System;FileTools;
"""


def extension_loader_content(command: list[str], *, python_paths: tuple[Path, ...] = ()) -> str:
    """Return the Nautilus loader shared by user and Debian package layouts."""

    path_setup = "".join(f"sys.path.insert(0, {str(path)!r})\n" for path in python_paths)
    import_setup = "import sys\n" if python_paths else ""
    return (
        f"{MARKER}\n"
        f"{import_setup}"
        f"{path_setup}"
        "from amigafs_nautilus import extension as _extension\n"
        f"_extension.configure_command({command!r})\n"
        "class AmigaFSMenuProvider(_extension.AmigaFSMenuProvider):\n"
        "    pass\n"
        "class AmigaFSPropertiesModelProvider(_extension.AmigaFSPropertiesModelProvider):\n"
        "    pass\n"
    )


def _refresh_database(command: str, directory: Path) -> None:
    if not directory.exists():
        return
    executable = shutil.which(command)
    if executable is None:
        return
    result = subprocess.run(
        [executable, str(directory)],
        check=False,
        capture_output=True,
        text=True,
    )
    if result.returncode:
        detail = result.stderr.strip() or f"{command} failed"
        raise AmigaFSError(f"Could not refresh desktop integration: {detail}")


def install_extension(*, restart: bool = False) -> Path:
    """Install the Nautilus extension, MIME definitions and desktop handler."""

    target = extension_path()
    _remove_if_generated(target.parent / LEGACY_EXTENSION_NAME)
    source_root = Path(__file__).resolve().parents[1]
    dependency_root = Path(sysconfig.get_path("purelib"))
    content = extension_loader_content(
        [sys.executable, "-m", "amigafs.cli"],
        python_paths=(dependency_root, source_root),
    )
    _write_generated(target, content)
    _write_generated(mime_package_path(), mime_package_content(), marker=XML_MARKER)
    _write_generated(desktop_file_path(), desktop_file_content())
    _refresh_database("update-mime-database", data_home() / "mime")
    _refresh_database("update-desktop-database", data_home() / "applications")
    if restart:
        subprocess.run(["nautilus", "--quit"], check=False)
    return target


def uninstall_extension(*, restart: bool = False) -> Path:
    """Remove only integration files generated by AmigaFS and refresh caches."""

    target = extension_path()
    _remove_if_generated(target)
    _remove_if_generated(target.parent / LEGACY_EXTENSION_NAME)
    _remove_if_generated(mime_package_path(), marker=XML_MARKER)
    _remove_if_generated(desktop_file_path())
    _refresh_database("update-mime-database", data_home() / "mime")
    _refresh_database("update-desktop-database", data_home() / "applications")
    if restart:
        subprocess.run(["nautilus", "--quit"], check=False)
    return target
